version: "3.8"

services:
  api:
    container_name: facebook-gift-api
    image: dockerdsm1.thegioiwhey.com/luannt201dev/facebook-gift-api:develop
    build:
      context: .
    ports:
      - "1298:3000"
    restart: always
    environment:
      - PORT=1298
      - SECRET=abc@123
      - ZALO_APP_ID=1090500091735806012
      - EXPIRED_TIME=10
      - MAX_POINT_PER_DAY=5
      - SAPOGO_URL=https://tgw.mysapogo.com/admin
      - SAPOGO_PROMOTION_TOKEN=cb146b4c3d6f4ee9884d91be62e647cc
      - ZALO_APP_SECRET_KEY=UASs1IvX3JJPcI8yL8H0

      - POSTGRES_ENABLE=true
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=dev
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=thegioiwhey@123

      - S3_ENABLE=true
      - BUCKET=tgw-core-app
      - REGION=ap-southeast-1
      - AWS_ACCESS_KEY=AKIAVMBVGMRN7BWBKYCI
      - AWS_SECRET_KEY=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
    network_mode: bridge
